### ISSUE TITLE
Bower for dependencies 

### ISSUE THREAD

**Issue by Fajkowsky** [michaldudak/fp-angular-js-training#1]
It's very good training. I have one question, why not use bower for dependencies? I mean you are using npm already so using bower should be handy also.

**Comment by michaldudak** [comment]
Good idea, thanks. Would you like to contibute?

**Comment by Fajkowsky** [comment]
Yes, sure! I will make changes in couple days you should be seeing my pull request.

**Comment by michaldudak** [comment]
"in couple days", yeah sure ;) 

Anyway, bower has recently been deprecated, so I'm going to close this issue.
